"""Initial migration

Revision ID: f5939049cc92
Revises: 
Create Date: 2024-08-12 11:06:30.596220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5939049cc92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_selenium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platforma', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zadatak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platforma', sa.String(length=150), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=False),
    sa.Column('komentar_na_koji_odgovaramo', sa.Text(), nullable=False),
    sa.Column('komentar', sa.Text(), nullable=False),
    sa.Column('komentarisano', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadatak')
    op.drop_table('user_selenium')
    op.drop_table('user')
    # ### end Alembic commands ###
